### ISSUE TITLE
Explicitly specify start and end times

### ISSUE THREAD

**Issue by jklina** [aws/aws-xray-sdk-ruby#10]
I was hoping to use this in conjunction with with Rails' notification system. See:

https://guides.rubyonrails.org/active_support_instrumentation.html

However the notifications rely on being able to explicitly record the `start_time` and `end_time` which I'm having trouble figuring out how to do with this gem. Specifically I'm trying to record SQL requests along with the the query:

```
ActiveSupport::Notifications.subscribe "sql.active_record" do |name, start, finish, id, payload|
  # Having trouble specifying times.
  # XRay.recorder.capture(:sql) do |thing|
  #   thing.segment.start_time = start.to_i
  #   thing.segment.end_time = finish.to_i
  #   XRay.recorder.metadata[:sql_query] = payload.fetch(:sql)
  # end
end
```

Is there currently away to do this that I'm missing or plans to add this ability. 

Thank you!

**Comment by haotianw465** [comment]
Hi, the SDK has a built-in active record capture for event `sql.active_record` https://github.com/aws/aws-xray-sdk-ruby/blob/master/lib/aws-xray-sdk/facets/rails/active_record.rb you can use as a reference. I would like to know which part of this implementation doesn't fit your requirement?

Please note that since the actual query might contain sensitive information, the SDK can only capture parameterized query, which is currently in our backlog but you are very welcome to submit a PR. Or you can choose to not use the built-in module and subscribe your own instrumentation.

Please let me know if this answers your question.
